const types = {
  SET_INCOME_CATEGORY: 'SET_INCOME_CATEGORY',
  SET_EXPENSE_CATEGORY: 'SET_EXPENSE_CATEGORY',
  SET_PAYMENTS: 'SET_PAYMENTS',
  SET_TAB_TYPE: 'SET_TAB_TYPE',
  SET_MONTH: 'CHANGE_MONTH',
  SET_ACCOUNT_TYPE: 'SET_ACCOUNT_TYPE',
  SET_ACCOUNT_LIST: 'SET_ACCOUNT_LIST',
  SET_ACCOUNT_TYPE: 'SET_ACCOUNT_TYPE',
  SET_ACCOUNT_OPTION: 'SET_ACCOUNT_OPTION',
};

export default types;
