const types = {
  SET_INCOME_CATEGORY: 'SET_INCOME_CATEGORY',
  SET_EXPENSE_CATEGORY: 'SET_EXPENSE_CATEGORY',
  SET_PAYMENTS: 'SET_PAYMENTS',
  SET_TAB_TYPE: 'SET_TAB_TYPE',
  NEXT_MONTH_PICKER: 'NEXT_MONTH_PICKER',
  PREVIOUS_MONTH_PICKER: 'PREVIOUS_MONTH_PICKER',
};

export default types;
